### ISSUE TITLE
Hub&Spoke setup is failing - free subscription quotalimit

### ISSUE THREAD

**Issue by pkosiol-cc** [azurecitadel/azurecitadel#110]
Hello together,

thanks for providing such a nice plattform for learning azure stuff. 😄 

The[ setup for the hub&spoke environment](https://www.azurecitadel.com/network/vdc/setup/) is failing because the setup is exceeding the quota for the free subscription. Would it be possible to update the setup-template that the deployment is not failing?

![image](https://user-images.githubusercontent.com/66460618/224980329-e49fbeaa-4bd3-476b-b3cc-f7f0a2a40418.png)

Best regards
Philipp Kosiol

**Comment by richeney** [comment]
Thanks Philip! Apologies for the slow response. 

I've reviewed the code and it looks as if there's only one public IP for the load balancer? 

If your subscription has already exhausted the quota of 3 then you could always remove one of the others to get the template to deploy. 

Note that you can delete a VM's public IP and it will continue to run and should still be able to access the internet and Azure endpoints.

I'll close this issue.
