### ISSUE TITLE
Add "COPY" functionality to make it easy to copy text from code blocks

### ISSUE THREAD

**Issue by mormond** [azurecitadel/azurecitadel#21]
Similar to functionality on docs.microsoft.com - make it easy to copy and paste code.

**Comment by jasoncabot-ms** [comment]
Should be fairly straightforward to add in JS, for example:

https://www.dannyguo.com/blog/how-to-add-copy-to-clipboard-buttons-to-code-blocks-in-hugo/

**Comment by jasoncabot-ms** [comment]
Fixed
