### ISSUE TITLE
Manual Onboarding - Success criteria

### ISSUE THREAD

**Issue by lufussel** [azurecitadel/azurecitadel#30]
**Bug exists on page**
https://www.azurecitadel.com/arc/servers-hack/manual/#success-criteria

**Describe the bug**
1. Show the connected VMs in the arc-demo resource group
should be `arc-hack`
3. Show the extensions are installed
no longer required

**To Reproduce**
NA

**Expected behavior**
As above

**Comment by richeney** [comment]
I think the rewritten lab pages are now solid so I'll close this one.
