### ISSUE TITLE
Scale Onboarding = Ansible host file

### ISSUE THREAD

**Issue by lufussel** [azurecitadel/azurecitadel#32]
**Bug exists on page**
https://www.azurecitadel.com/arc/servers-hack/scale/#additional-vms

**Describe the bug**
"Create an Ansible hosts file" is not explicit enough, had members of the team create their own Ansible files (which I don't think is the intent of the hack?)

**To Reproduce**
NA

**Expected behavior**
"Update the Terraform variables to create an Ansible hosts file"
or
Explicitly set the variable in `terraform.tfvars` so attendees are aware
or
Does this affect the initial challenges if this is default to `true`?

**Comment by richeney** [comment]
Ansible pulled out of those pages. Closing.
