### ISSUE TITLE
Use Bastion?

### ISSUE THREAD

**Issue by lufussel** [azurecitadel/azurecitadel#33]
It didn't block anyones deployment, but could be worth using Bastion to access the VMs rather than direct? I assume this doesn't conflict with Arc?

**Comment by richeney** [comment]
@lufussel I'm not sure what you mean by this? Is this related to some specific labs? Or to the azurecitadel site itself?

**Comment by lufussel** [comment]
Hi @richeney , this was related to the Azure Arc & Management hack (early run of it last year). Apologies that I somehow failed to tag this against something more specific!

**Comment by richeney** [comment]
No problem! I did have it working with selected source IP addresses, but I think I'll switch it to AAD auth and Bastion with native. You know, as I have a nice repo for it! https://github.com/terraform-azurerm-examples/bastion

**Comment by richeney** [comment]
OK if I close?

**Comment by lufussel** [comment]
Certainly sir, thank you!
