### ISSUE TITLE
K8s hack - background

### ISSUE THREAD

**Issue by lufussel** [azurecitadel/azurecitadel#40]
**Bug exists on page**
https://github.com/azurecitadel/azurecitadel/blob/aks-arc-hack/content/arc/k8s-hack/background.md

**Describe the bug**
"Use the hack template project to create a team repository on GitHub that everyone can collaborate on"
**hack template project** -- needs a link to the hack template project! Also add to References?

**Expected behavior**
Link please?

**Comment by jasoncabot-ms** [comment]
Fixed
