### ISSUE TITLE
How to connect through to the on premises VMs?

### ISSUE THREAD

**Issue by lufussel** [azurecitadel/azurecitadel#95]
**Bug exists on page**
https://www.azurecitadel.com/arc/servers/linux/

**Describe the bug**
It's not clear where the VMs are or how to connect to them (as they're not in the Azure portal), some more description in this page will help, and to reference to finding the access details in the channel wiki.

Also, the IP addresses for firewall rules are needed at this point, a reminder here is useful too.

**Comment by richeney** [comment]
I think we've addressed this with the twin Azure Pass approach and reworked docs, so I'll close.
